// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4Assignment.Models;

namespace Mission4Assignment.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20220218011117_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4Assignment.Models.Applicationresponse", b =>
                {
                    b.Property<string>("MovieTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RatingID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RatingID1")
                        .HasColumnType("INTEGER");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieTitle");

                    b.HasIndex("RatingID1");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieTitle = "cars",
                            Category = "Animation",
                            Director = "Disney",
                            Edited = "No",
                            LentTo = "no one",
                            Notes = "cinematic masterpiece",
                            RatingID = "G",
                            Year = (ushort)2007
                        },
                        new
                        {
                            MovieTitle = "Up",
                            Category = "Animation",
                            Director = "Disney",
                            Edited = "No",
                            LentTo = "no one",
                            Notes = "amazing cinematic masterpiece",
                            RatingID = "G",
                            Year = (ushort)2009
                        });
                });

            modelBuilder.Entity("Mission4Assignment.Models.Rating", b =>
                {
                    b.Property<int>("RatingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("RatingID");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Mission4Assignment.Models.Applicationresponse", b =>
                {
                    b.HasOne("Mission4Assignment.Models.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingID1");
                });
#pragma warning restore 612, 618
        }
    }
}
