// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4Assignment.Models;

namespace Mission4Assignment.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4Assignment.Models.Applicationresponse", b =>
                {
                    b.Property<string>("MovieTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieTitle");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieTitle = "cars",
                            Category = "Animation",
                            Director = "Disney",
                            Edited = "No",
                            LentTo = "no one",
                            Notes = "cinematic masterpiece",
                            Rating = "G",
                            Year = (ushort)2007
                        },
                        new
                        {
                            MovieTitle = "Up",
                            Category = "Animation",
                            Director = "Disney",
                            Edited = "No",
                            LentTo = "no one",
                            Notes = "amazing cinematic masterpiece",
                            Rating = "G",
                            Year = (ushort)2009
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
